@echo off
@echo > nul

rem change console to UTF-8
chcp 65001 > nul

rem 0.7.0.1
rem delete: Ɛ* files , However, the game creates these files with each login session.
rem del /f /q Ɛ*

if exist "Ɛ*" (
    del /f /q "Ɛ*"
    echo deleted cache files generated by pubg lite
) else (
    echo.
)

setlocal

rem Detect the absolute path of the folder where the .bat is located
set GAME_PATH=%~dp0


rem COMMENT: Start the game with the local Lobby files
start "" "PUBGLite-Win64-Shipping.exe" -UI -LobbyUrl="file:///%GAME_PATH%custom_lobby/index.html" ^
-AllowJoinAnyMatchState -stdout -LOG -cmd -NOSPLASH -nothreadtimeout 


rem COMMENT: Start the game using an online url
rem @PUBGLite-Win64-Shipping.exe -UI -LobbyUrl="https://phikill.github.io/RE_PUBG_LITE/custom_lobby/index.html" ^
rem -AllowJoinAnyMatchState -stdout -LOG -cmd -NOSPLASH -nothreadtimeout 



rem pause