#ifndef _LAUNCHERVIEW_ERRORCODES_H_
#define _LAUNCHERVIEW_ERRORCODES_H_


typedef struct 
{
	int ERROR_SUCCESS = 0;
	int ERROR_SERVICE_ALREADY_RUNNING = 1056;
	int ERROR_PRODUCT_UNINSTALLED = 1614;
	int ERROR_NOT_SUPPORTED = 50;
	int ERROR_UNKNOWN = 65535;
	
} Lview_ErrorCodes;







#endif /* _LAUNCHERVIEW_ERRORCODES_H_ */
