#ifndef _LAUNCHERVIEW_ERRORCODES_H_
#define _LAUNCHERVIEW_ERRORCODES_H_


#ifdef ERROR_SUCCESS 
	#undef ERROR_SUCCESS
	#define ERROR_SUCCESS 0
#endif 

#ifdef ERROR_SERVICE_ALREADY_RUNNING
	#undef ERROR_SERVICE_ALREADY_RUNNING
	#define ERROR_SERVICE_ALREADY_RUNNING 1056
#endif


#ifdef ERROR_PRODUCT_UNINSTALLED
	#undef ERROR_PRODUCT_UNINSTALLED
	#define ERROR_PRODUCT_UNINSTALLED 1614
#endif


#ifdef ERROR_NOT_SUPPORTED
	#undef ERROR_NOT_SUPPORTED
	#define ERROR_NOT_SUPPORTED 50
#endif


#ifdef ERROR_UNKNOWN
	#undef ERROR_UNKNOWN
	#define ERROR_UNKNOWN 65535
#endif







#endif /* _LAUNCHERVIEW_ERRORCODES_H_ */
